### ISSUE TITLE
Variant request

### ISSUE THREAD

**Issue by duhimhype** [dsvipeer/SpikesStripsCustom#1]
Can this be edited to a second version included to pop all tires? not everyone uses npcs

**Comment by dsvipeer** [comment]
> Can this be edited to a second version included to pop all tires? not everyone uses npcs

> Yes, this was an old project that I made for my own server and decided to post it for anyone wanting, so you can fork it and edit to match your liking.

**Comment by dsvipeer** [comment]
I'm quite busy with my life so I can't modify but feel free to mess around with it :)
